
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms_database?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ROOT123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: LMS
  mail:
    host: smtp.gmail.com
    port: 587
    username: emyelnassag@gmail.com
    password: ysnc cqbl uqcp csrf
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
server:
  port: 9090

